### ISSUE TITLE
java.sql.SQLSyntaxErrorException: Table 'playersync.server_info' doesn't exist

### ISSUE THREAD

**Issue by FortyTwoCn** [mlus-asuka/PlayerSync#10]
[20:31:13] [PlayerSync-thread-0/WARN]: java.sql.SQLSyntaxErrorException: Table 'playersync.server_info' doesn't exist
[20:31:13] [PlayerSync-thread-0/WARN]:  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[20:31:13] [PlayerSync-thread-0/WARN]:  at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:12
2)
[20:31:13] [PlayerSync-thread-0/WARN]:  at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[20:31:13] [PlayerSync-thread-0/WARN]:  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098
)
[20:31:13] [PlayerSync-thread-0/WARN]:  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046
)
[20:31:13] [PlayerSync-thread-0/WARN]:  at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
[20:31:13] [PlayerSync-thread-0/WARN]:  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
[20:31:13] [PlayerSync-thread-0/WARN]:  at vip.fubuki.playersync.util.JDBCsetUp.executeUpdate(JDBCsetUp.java:35)
[20:31:13] [PlayerSync-thread-0/WARN]:  at vip.fubuki.playersync.sync.VanillaSync.doPlayerSaveToFile(VanillaSync.java:159)
[20:31:13] [PlayerSync-thread-0/WARN]:  at vip.fubuki.playersync.sync.VanillaSync.lambda$onPlayerSaveToFile$1(VanillaSync.java:171)
[20:31:13] [PlayerSync-thread-0/WARN]:  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:31:13] [PlayerSync-thread-0/WARN]:  at java.util.concurrent.FutureTask.run(Unknown Source)
[20:31:13] [PlayerSync-thread-0/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:31:13] [PlayerSync-thread-0/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:31:13] [PlayerSync-thread-0/WARN]:  at java.lang.Thread.run(Unknown Source)

**Comment by mlus-asuka** [comment]
删数据库重建。你是不是以前用过老版本的

**Comment by FortyTwoCn** [comment]
还是不行 我用的是Mysql8

**Comment by FortyTwoCn** [comment]
> 删数据库重建。你是不是以前用过老版本的

删了，还是不行 用的MySQL8

**Comment by mlus-asuka** [comment]
https://github.com/mlus-asuka/PlayerSync/releases/tag/beta

**Comment by FortyTwoCn** [comment]
> https://github.com/mlus-asuka/PlayerSync/releases/tag/beta

加个QQ吧 现在问题更加严重了 2706560674

**Comment by FortyTwoCn** [comment]
[13:34:39] [Server thread/ERROR]: Exception caught during firing event: You have an error in your SQL syntax; check the manual that correspo
nds to your MySQL server version for the right syntax to use near 'UPDATE server_info SET enable=false WHERE id=1831970349' at line 1
        Index: 3
        Listeners:
                0: HIGH
                1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/fml/event/server/FMLSer
verStoppedEvent;)V
                2: NORMAL
                3: ASM: class vip.fubuki.playersync.sync.VanillaSync onServerShutdown(Lnet/minecraftforge/fml/event/server/FMLServerStoppedE
vent;)V
                4: net.minecraftforge.eventbus.EventBus$$Lambda$2795/1070020292@773956bc
                5: ASM: class snownee.kiwi.schedule.Scheduler serverStopped(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
                6: net.minecraftforge.eventbus.EventBus$$Lambda$2795/1070020292@5cb72856
                7: net.minecraftforge.eventbus.EventBus$$Lambda$2795/1070020292@6019583d
                8: net.minecraftforge.eventbus.EventBus$$Lambda$2795/1070020292@4ef76c1f
                9: ASM: class sonar.fluxnetworks.register.CommonEventHandler onServerStopped(Lnet/minecraftforge/fml/event/server/FMLServerS
toppedEvent;)V
                10: net.minecraftforge.eventbus.EventBus$$Lambda$2795/1070020292@73c64fcb
                11: net.minecraftforge.eventbus.EventBus$$Lambda$2795/1070020292@16562c7d
                12: ASM: top.theillusivec4.polymorph.common.CommonEventsListener@1017a6ea serverStopped(Lnet/minecraftforge/fml/event/server
/FMLServerStoppedEvent;)V
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for t
he right syntax to use near 'UPDATE server_info SET enable=false WHERE id=1831970349' at line 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
        at vip.fubuki.playersync.util.JDBCsetUp.executeUpdate(JDBCsetUp.java:30)
        at vip.fubuki.playersync.sync.VanillaSync.onServerShutdown(VanillaSync.java:180)
        at net.minecraftforge.eventbus.ASMEventHandler_21_VanillaSync_onServerShutdown_FMLServerStoppedEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:303)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:124)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:822)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265)
        at java.lang.Thread.run(Unknown Source)

[13:34:39] [Server thread/ERROR]: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds
to your MySQL server version for the right syntax to use near 'UPDATE server_info SET enable=false WHERE id=1831970349' at line 1
