### ISSUE TITLE
1.18.2forge / Mysql8 启动失败

### ISSUE THREAD

**Issue by THYuyukoZLAK** [mlus-asuka/PlayerSync#12]
```
[07Feb2024 12:57:28.533] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS player_data (uuid CHAR(36) NOT NULL,inventory MEDIUMB' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[MySQL-561280-3685108.jar%23283!/:?]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[MySQL-561280-3685108.jar%23283!/:?]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[MySQL-561280-3685108.jar%23283!/:?]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098) ~[MySQL-561280-3685108.jar%23283!/:?]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046) ~[MySQL-561280-3685108.jar%23283!/:?]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371) ~[MySQL-561280-3685108.jar%23283!/:?]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031) ~[MySQL-561280-3685108.jar%23283!/:?]
	at vip.fubuki.playersync.util.JDBCsetUp.executeUpdate(JDBCsetUp.java:38) ~[playersync-1.18.2-1.2.1-all.jar%23165!/:1.18.2-1.2.1]
	at vip.fubuki.playersync.util.JDBCsetUp.executeUpdate(JDBCsetUp.java:27) ~[playersync-1.18.2-1.2.1-all.jar%23165!/:1.18.2-1.2.1]
	at vip.fubuki.playersync.PlayerSync.onServerStarting(PlayerSync.java:46) ~[playersync-1.18.2-1.2.1-all.jar%23165!/:1.18.2-1.2.1]
	at net.minecraftforge.eventbus.ASMEventHandler_5_PlayerSync_onServerStarting_ServerStartingEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:98) ~[forge-1.18.2-40.2.11-universal.jar%23221!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:207) ~[server-1.18.2-20220404.173914-srg.jar%23216!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.18.2-20220404.173914-srg.jar%23216!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23216!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

full crash-report: https://pastebin.com/DaQgw7P9

**Comment by mlus-asuka** [comment]
Fixed in 1.18.2-1.3.0
