### ISSUE TITLE
1.18.2forge / 1.3.0 安装后无法进入服务器

### ISSUE THREAD

**Issue by THYuyukoZLAK** [mlus-asuka/PlayerSync#13]
如果有两个服务器安装并加载模组，客户端试图进入服务器时会收到`playersync.already_online`  
如果只有一个服务端运行则能够正常进入服务器。  
尝试连接服务器时服务端相关日志：  
```
[18Feb2024 00:37:03.222] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: THYuyuko_051130[/113.133.155.50:12225] logged in with entity id 969 at (32193.36403237995, 84.24433192162623, -234.33322440630047)
[18Feb2024 00:37:03.248] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: THYuyuko_051130 joined the game
[18Feb2024 00:37:03.309] [Server thread/INFO] [org.zeith.solarflux.SolarFlux/]: Sending solar panels to THYuyuko_051130.
[18Feb2024 00:37:03.685] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: THYuyuko_051130 lost connection: playersync.already_online
[18Feb2024 00:37:03.685] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: THYuyuko_051130 left the game
```
可能有关的服务端相关日志：（出现在第二个服务端启动过程中已启动完成的服务端日志内）  
```
java.sql.SQLException: Incorrect integer value: 'false' for column 'online' at row 1
        at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
        at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
        at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
        at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
        at TRANSFORMER/playersync@1.18.2-1.3.0/vip.fubuki.playersync.util.JDBCsetUp.executeUpdate(JDBCsetUp.java:32)
        at TRANSFORMER/playersync@1.18.2-1.3.0/vip.fubuki.playersync.sync.VanillaSync.doPlayerLogout(VanillaSync.java:187)
        at TRANSFORMER/playersync@1.18.2-1.3.0/vip.fubuki.playersync.sync.VanillaSync.lambda$onPlayerLogout$2(VanillaSync.java:199)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mlus-asuka** [comment]
试一下这个build
https://github.com/mlus-asuka/PlayerSync/actions/runs/7957404179

**Comment by THYuyukoZLAK** [comment]
可以正常工作了
