### ISSUE TITLE
java.sql.SQLException: Incorrect integer value: 'false' for column 'enable' at row 1

### ISSUE THREAD

**Issue by rdaniels0906** [mlus-asuka/PlayerSync#14]
Server thread/ERROR14:45:29
Uncaught exception in server thread
java.sql.SQLException: Incorrect integer value: 'false' for column 'enable' at row 1
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[MySQL-561280-3685108.jar%23477!/:?] {re:classloading}
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[MySQL-561280-3685108.jar%23477!/:?] {re:classloading}
at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[MySQL-561280-3685108.jar%23477!/:?] {re:classloading}
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098) ~[MySQL-561280-3685108.jar%23477!/:?] {re:classloading}
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046) ~[MySQL-561280-3685108.jar%23477!/:?] {re:classloading}
at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371) ~[MySQL-561280-3685108.jar%23477!/:?] {re:classloading}
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031) ~[MySQL-561280-3685108.jar%23477!/:?] {re:classloading}
at vip.fubuki.playersync.util.JDBCsetUp.executeUpdate(JDBCsetUp.java:32) ~[playersync-1.20.1-1.3.0-all.jar%23335!/:1.20.1-1.3.0] {re:classloading}
at vip.fubuki.playersync.sync.VanillaSync.onServerShutdown(VanillaSync.java:181) ~[playersync-1.20.1-1.3.0-all.jar%23335!/:1.20.1-1.3.0] {re:classloading}
at vip.fubuki.playersync.sync.__VanillaSync_onServerShutdown_ServerStoppedEvent.invoke(.dynamic) ~[playersync-1.20.1-1.3.0-all.jar%23335!/:1.20.1-1.3.0] {re:classloading,pl:eventbus:B}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:133) ~[forge-1.20.1-47.2.18-universal.jar%23380!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:697) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]

**Comment by rdaniels0906** [comment]
java.sql.SQLException: Incorrect integer value: 'true' for column 'online' at row 1
at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
at TRANSFORMER/mysql_jdbc@8.0.28+20220312/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
at TRANSFORMER/playersync@1.20.1-1.3.0/vip.fubuki.playersync.util.JDBCsetUp.executeUpdate(JDBCsetUp.java:32)
at TRANSFORMER/playersync@1.20.1-1.3.0/vip.fubuki.playersync.sync.VanillaSync.doPlayerJoin(VanillaSync.java:75)
at TRANSFORMER/playersync@1.20.1-1.3.0/vip.fubuki.playersync.sync.VanillaSync.lambda$OnPlayerJoin$0(VanillaSync.java:145)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by mlus-asuka** [comment]
are you using 1.18.2?
try this instead https://github.com/mlus-asuka/PlayerSync/actions/runs/7957404179

**Comment by rdaniels0906** [comment]
its 1.20.1

**Comment by mlus-asuka** [comment]
sry,I forget to upload it. you could download 1.3.1 in cf soon

**Comment by rdaniels0906** [comment]
resolved. thank you very much.
