### ISSUE TITLE
与mohist不兼容

### ISSUE THREAD

**Issue by starxjys** [mlus-asuka/PlayerSync#21]
这是报错
```
[16:02:09 INFO]: ImmediateWindowProvider not loading because launch target is forgeserver
[16:02:09 INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/Server/mohist/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23113!/ Service=ModLauncher Env=SERVER
[16:02:09 WARN]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File:
[16:02:09 INFO]: Found 20 dependencies adding them to mods collection
Exception in thread "main" java.lang.module.ResolutionException: Modules mysql_jdbc and mysql.connector.j export package com.mysql.cj.conf to module pineapple_delight
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:115)
```

问了一下gpt，说有两个MySQL 依赖。

我就把mohist的libraries里的mysql.connector.j删了，是可以正常启动的。

感觉可以检查一下环境中的mysql.connector.j

**Comment by mlus-asuka** [comment]
可以用git action里的构建 带 all的是有connector的。不带的是没有的

**Comment by starxjys** [comment]
> 可以用git action里的构建 带 all的是有connector的。不带的是没有的

已解决，感谢感谢！
