### ISSUE TITLE
与“神秘遗物”中的“迷人徽章”冲突

### ISSUE THREAD

**Issue by starxjys** [mlus-asuka/PlayerSync#22]
日志：
[https://pastebin.com/QyHCHsfK](https://pastebin.com/QyHCHsfK)
```
[08:54:02] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus]: Exception caught during firing event: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{"text":"111"}'}|tagDisplayEnabled:0b}}}' WHERE uuid = '56aaed6f-de60-3aeb-a6a3-' at line 1
```
复现办法：
佩戴改名后的迷人徽章，退出服务器

可稳定复现（mohist）

另外下面这个异步警告不知道用不用管

```
[08:53:48] [PlayerSync-thread-2/WARN] []: java.lang.IllegalStateException: EntityPotionEffectEvent cannot be triggered asynchronously from another thread.
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at TRANSFORMER/forge@47.3.10/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:583)
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at TRANSFORMER/forge@47.3.10/org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactory.java:1658)
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at TRANSFORMER/forge@47.3.10/org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactory.java:1637)
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_21219_(LivingEntity.java:1014)
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at TRANSFORMER/playersync@1.20.1-1.3.3/vip.fubuki.playersync.sync.VanillaSync.doPlayerJoin(VanillaSync.java:108)
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at TRANSFORMER/playersync@1.20.1-1.3.3/vip.fubuki.playersync.sync.VanillaSync.lambda$OnPlayerJoin$0(VanillaSync.java:147)
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[08:53:48] [PlayerSync-thread-2/WARN] []: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by mlus-asuka** [comment]
应该是这个物品的nbt中有特殊字符。可以用kubejs之类的工具获取nbt看看吗

**Comment by starxjys** [comment]
我拿NBTExplorer看了一下

![Snipaste_2024-09-21_08-40-22](https://github.com/user-attachments/assets/85c754ca-aa17-4cf5-8bd4-9dee4adfc098)

**Comment by mlus-asuka** [comment]
https://github.com/mlus-asuka/PlayerSync/actions/runs/11015148441
你这应该是放背包不会崩放饰品栏崩了吧。用新构建的版本试试

**Comment by starxjys** [comment]
> https://github.com/mlus-asuka/PlayerSync/actions/runs/11015148441 你这应该是放背包不会崩放饰品栏崩了吧。用新构建的版本试试

对的，在饰品栏会崩。感谢大佬，已修复
