### ISSUE TITLE
[1.20.1] 报错：`java.lang.IllegalStateException: EntityPotionEffectEvent cannot be triggered asynchronously from another thread.`

### ISSUE THREAD

**Issue by BredyAK** [mlus-asuka/PlayerSync#24]
这个错误会在玩家加入游戏时发生，并且很多玩家加入游戏会导致这个错误刷屏。错误日志片段如下：
```
[09:12:33 INFO]: BredyAK[/***.***.***.***:***] logged in with entity id 208 at ([world]18.06735143130136, 83.0, 13.906782238030077)
[09:12:33 WARN]: java.lang.IllegalStateException: EntityPotionEffectEvent cannot be triggered asynchronously from another thread.
[09:12:33 WARN]:        at TRANSFORMER/forge@47.3.10/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:583)
[09:12:33 WARN]:        at TRANSFORMER/forge@47.3.10/org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactory.java:1658)
[09:12:33 WARN]:        at TRANSFORMER/forge@47.3.10/org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactory.java:1637)
[09:12:33 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_21219_(LivingEntity.java:1014)
[09:12:33 WARN]:        at TRANSFORMER/playersync@1.20.1-1.3.3/vip.fubuki.playersync.sync.VanillaSync.doPlayerJoin(VanillaSync.java:107)
[09:12:33 WARN]:        at TRANSFORMER/playersync@1.20.1-1.3.3/vip.fubuki.playersync.sync.VanillaSync.lambda$onPlayerJoin$0(VanillaSync.java:146)
[09:12:33 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[09:12:33 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[09:12:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[09:12:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[09:12:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by mlus-asuka** [comment]
你用的这个核心不支持异步。

**Comment by BredyAK** [comment]
> 你用的这个核心不支持异步。

我的核心是 Mohist。

**Comment by mlus-asuka** [comment]
> > 你用的这个核心不支持异步。
> 
> 我的核心是 Mohist。

这个报错其实不影响任何实际功能。

**Comment by BredyAK** [comment]
> > > 你用的这个核心不支持异步。
> > 
> > 
> > 我的核心是 Mohist。
> 
> 这个报错其实不影响任何实际功能。

人多起来以后，这个报错比较刷屏……既然不影响实际功能，那么是否可以考虑删除这个报错？

**Comment by mlus-asuka** [comment]
这是核心报的错。你可以找个关键词屏蔽日志的插件把asynchronously有关的都屏蔽了

**Comment by BredyAK** [comment]
好的，谢谢作者大大，那么此 issue 就先关闭了。
