### ISSUE TITLE
[1.20.1] 使用 #25 中修复的版本后，服务器启动失败：`Exception caught during firing event: You have an error in your SQL syntax`

### ISSUE THREAD

**Issue by BredyAK** [mlus-asuka/PlayerSync#26]
问题描述：切换模组至 #25 中修复的版本后，服务器启动失败，并报错 `Exception caught during firing event: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cursor blob' at line 3`。详情请见下方完整启动日志。
服务器完整启动日志：[https://mclo.gs/IFlJfrV](https://mclo.gs/IFlJfrV)（第 1048 至 1108 行）

**Comment by mlus-asuka** [comment]
https://github.com/mlus-asuka/PlayerSync/actions/runs/11287126363
漏打了一个s

**Comment by BredyAK** [comment]
> https://github.com/mlus-asuka/PlayerSync/actions/runs/11287126363 漏打了一个s

只要玩家加入服务器，就会出现新的报错：
```
[14:11:03 INFO]: BredyAK[/***.***.***.***:***] logged in with entity id 201 at ([world]-10.5, 99.0, -9.5)
[14:11:03 WARN]: java.sql.SQLSyntaxErrorException: Unknown column 'left_hand' in 'field list'
[14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
[14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
[14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
[14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
[14:11:03 WARN]:        at TRANSFORMER/playersync@1.20.1-1.3.4/vip.fubuki.playersync.util.JDBCsetUp.executeUpdate(JDBCsetUp.java:34)
[14:11:03 WARN]:        at TRANSFORMER/playersync@1.20.1-1.3.4/vip.fubuki.playersync.sync.VanillaSync.store(VanillaSync.java:278)
[14:11:03 WARN]:        at TRANSFORMER/playersync@1.20.1-1.3.4/vip.fubuki.playersync.sync.VanillaSync.doPlayerJoin(VanillaSync.java:50)
[14:11:03 WARN]:        at TRANSFORMER/playersync@1.20.1-1.3.4/vip.fubuki.playersync.sync.VanillaSync.lambda$onPlayerJoin$0(VanillaSync.java:151)
[14:11:03 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[14:11:03 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[14:11:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:11:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[14:11:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```
并且实际上副手物品并未成功同步。

**Comment by mlus-asuka** [comment]
你的表应该出了什么问题，手动执行SQL语句或者再重启一下试试
``` 
ALTER TABLE player_data
ADD COLUMN left_hand blob,
ADD COLUMN cursors blob;
```

**Comment by BredyAK** [comment]
> 你的表应该出了什么问题，手动执行SQL语句或者再重启一下试试
> 
> ```
> ALTER TABLE player_data
> ADD COLUMN left_hand blob,
> ADD COLUMN cursors blob;
> ```

测试是在新的 MySQL 且没有表的情况下进行的。刚才又重新测了一遍，还是一样的问题。

**Comment by BredyAK** [comment]
> > https://github.com/mlus-asuka/PlayerSync/actions/runs/11287126363 漏打了一个s
> 
> 只要玩家加入服务器，就会出现新的报错：
> 
> ```
> [14:11:03 INFO]: BredyAK[/***.***.***.***:***] logged in with entity id 201 at ([world]-10.5, 99.0, -9.5)
> [14:11:03 WARN]: java.sql.SQLSyntaxErrorException: Unknown column 'left_hand' in 'field list'
> [14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
> [14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
> [14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
> [14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
> [14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
> [14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
> [14:11:03 WARN]:        at MC-BOOTSTRAP/mysql.connector.j@8.0.33/com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
> [14:11:03 WARN]:        at TRANSFORMER/playersync@1.20.1-1.3.4/vip.fubuki.playersync.util.JDBCsetUp.executeUpdate(JDBCsetUp.java:34)
> [14:11:03 WARN]:        at TRANSFORMER/playersync@1.20.1-1.3.4/vip.fubuki.playersync.sync.VanillaSync.store(VanillaSync.java:278)
> [14:11:03 WARN]:        at TRANSFORMER/playersync@1.20.1-1.3.4/vip.fubuki.playersync.sync.VanillaSync.doPlayerJoin(VanillaSync.java:50)
> [14:11:03 WARN]:        at TRANSFORMER/playersync@1.20.1-1.3.4/vip.fubuki.playersync.sync.VanillaSync.lambda$onPlayerJoin$0(VanillaSync.java:151)
> [14:11:03 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
> [14:11:03 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
> [14:11:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [14:11:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [14:11:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
> ```
> 
> 并且实际上副手物品并未成功同步。

加入游戏、退出游戏均会触发这一错误。

**Comment by mlus-asuka** [comment]
嗯，我知道为什么了。但是你手动执行一下sql就可以正常用了

**Comment by BredyAK** [comment]
> 嗯，我知道为什么了。但是你手动执行一下sql就可以正常用了

可以期待下一个版本什么时候发布吗？🤤

**Comment by mlus-asuka** [comment]
已上传CF。过审要一阵子
